// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identities.sql

package authdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (user_id, provider, provider_id, credential_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, provider_id, credential_hash, created_at
`

type CreateIdentityParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	Provider       string         `json:"provider"`
	ProviderID     string         `json:"provider_id"`
	CredentialHash sql.NullString `json:"credential_hash"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.CredentialHash,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.CredentialHash,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityByProvider = `-- name: GetIdentityByProvider :one
SELECT i.id, i.user_id, i.provider, i.provider_id, i.credential_hash, i.created_at
FROM identities i
JOIN users u ON u.id = i.user_id
WHERE i.provider = $1
  AND i.provider_id = $2
  AND u.tenant_id = $3
LIMIT 1
`

type GetIdentityByProviderParams struct {
	Provider   string    `json:"provider"`
	ProviderID string    `json:"provider_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetIdentityByProvider(ctx context.Context, arg GetIdentityByProviderParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByProvider, arg.Provider, arg.ProviderID, arg.TenantID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.CredentialHash,
		&i.CreatedAt,
	)
	return i, err
}
