// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignPermissionsToRole(ctx context.Context, arg AssignPermissionsToRoleParams) error
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetIdentityByProvider(ctx context.Context, arg GetIdentityByProviderParams) (Identity, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]string, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListRoles(ctx context.Context, tenantID uuid.UUID) ([]Role, error)
	ReplaceRolePermissions(ctx context.Context, roleID uuid.UUID) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (Permission, error)
}

var _ Querier = (*Queries)(nil)
