// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package authdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const assignPermissionsToRole = `-- name: AssignPermissionsToRole :exec
INSERT INTO role_permissions (role_id, permission_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type AssignPermissionsToRoleParams struct {
	RoleID  uuid.UUID   `json:"role_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) AssignPermissionsToRole(ctx context.Context, arg AssignPermissionsToRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignPermissionsToRole, arg.RoleID, pq.Array(arg.Column2))
	return err
}

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.ExecContext(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (tenant_id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, slug, created_at
`

type CreateRoleParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Slug     string    `json:"slug"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.TenantID, arg.Name, arg.Slug)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, tenant_id, name, slug, created_at FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, tenant_id, name, slug, created_at FROM roles
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context, tenantID uuid.UUID) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceRolePermissions = `-- name: ReplaceRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) ReplaceRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, replaceRolePermissions, roleID)
	return err
}
